buildings_final_demand_crude_oil_buildings_final_demand_for_space_heating_crude_oil_parent_share:
  variable: mq_buildings_final_demand_crude_oil_buildings_final_demand_for_space_heating_crude_oil_parent_share
