buildings_final_demand_wood_pellets_buildings_final_demand_for_appliances_wood_pellets_parent_share:
  variable: mq_buildings_final_demand_wood_pellets_buildings_final_demand_for_appliances_wood_pellets_parent_share
