buildings_final_demand_for_lighting_electricity_buildings_lighting_led_electricity_parent_share:
  variable: mq_buildings_final_demand_for_lighting_electricity_buildings_lighting_led_electricity_parent_share
