buildings_final_demand_crude_oil_buildings_final_demand_for_appliances_crude_oil_parent_share:
  variable: mq_buildings_final_demand_crude_oil_buildings_final_demand_for_appliances_crude_oil_parent_share
