buildings_final_demand_network_gas_buildings_final_demand_for_appliances_network_gas_parent_share:
  variable: mq_buildings_final_demand_network_gas_buildings_final_demand_for_appliances_network_gas_parent_share
