buildings_final_demand_for_cooling_electricity_buildings_cooling_heatpump_air_water_electricity_parent_share:
  variable: mq_buildings_final_demand_for_cooling_electricity_buildings_cooling_heatpump_air_water_electricity_parent_share
