buildings_final_demand_electricity_buildings_final_demand_for_space_heating_electricity_parent_share:
  variable: mq_buildings_final_demand_electricity_buildings_final_demand_for_space_heating_electricity_parent_share
