households_final_demand_electricity_households_final_demand_for_lighting_electricity_parent_share:
  variable: mq_households_final_demand_electricity_households_final_demand_for_lighting_electricity_parent_share
