households_final_demand_for_space_heating_network_gas_households_space_heater_network_gas_parent_share:
  variable: mq_households_final_demand_for_space_heating_network_gas_households_space_heater_network_gas_parent_share
