households_final_demand_for_appliances_electricity_households_appliances_dishwasher_electricity_parent_share:
  variable: mq_households_final_demand_for_appliances_electricity_households_appliances_dishwasher_electricity_parent_share
