households_final_demand_network_gas_households_final_demand_for_space_heating_network_gas_parent_share:
  variable: mq_households_final_demand_network_gas_households_final_demand_for_space_heating_network_gas_parent_share
