households_final_demand_wood_pellets_households_final_demand_for_space_heating_wood_pellets_parent_share:
  variable: mq_households_final_demand_wood_pellets_households_final_demand_for_space_heating_wood_pellets_parent_share
