households_final_demand_network_gas_households_final_demand_for_hot_water_network_gas_parent_share:
  variable: mq_households_final_demand_network_gas_households_final_demand_for_hot_water_network_gas_parent_share
