households_final_demand_for_lighting_electricity_households_lighting_efficient_fluorescent_electricity_parent_share:
  variable: mq_households_final_demand_for_lighting_electricity_households_lighting_efficient_fluorescent_electricity_parent_share
