households_final_demand_for_appliances_electricity_households_appliances_washing_machine_electricity_parent_share:
  variable: mq_households_final_demand_for_appliances_electricity_households_appliances_washing_machine_electricity_parent_share
