households_final_demand_for_cooling_electricity_households_cooling_heatpump_ground_water_electricity_parent_share:
  variable: mq_households_final_demand_for_cooling_electricity_households_cooling_heatpump_ground_water_electricity_parent_share
