households_final_demand_for_cooking_electricity_households_cooker_halogen_electricity_parent_share:
  variable: mq_households_final_demand_for_cooking_electricity_households_cooker_halogen_electricity_parent_share
