households_final_demand_crude_oil_households_final_demand_for_hot_water_crude_oil_parent_share:
  variable: mq_households_final_demand_crude_oil_households_final_demand_for_hot_water_crude_oil_parent_share
