industry_final_demand_for_metal_steel_electricity_industry_steel_blastfurnace_bof_parent_share:
  variable: mq_industry_final_demand_for_metal_steel_electricity_industry_steel_blastfurnace_bof_parent_share
