industry_final_demand_for_metal_aluminium_electricity_industry_aluminium_smeltoven_electricity_parent_share:
  variable: mq_industry_final_demand_for_metal_aluminium_electricity_industry_aluminium_smeltoven_electricity_parent_share
