industry_final_demand_for_other_paper_electricity_industry_other_paper_heater_electricity_parent_share:
  variable: mq_industry_final_demand_for_other_paper_electricity_industry_other_paper_heater_electricity_parent_share
