industry_final_demand_for_metal_steel_crude_oil_industry_steel_blastfurnace_bof_parent_share:
  variable: mq_industry_final_demand_for_metal_steel_crude_oil_industry_steel_blastfurnace_bof_parent_share
