industry_final_demand_for_other_food_electricity_industry_other_food_heater_electricity_parent_share:
  variable: mq_industry_final_demand_for_other_food_electricity_industry_other_food_heater_electricity_parent_share
