industry_final_demand_for_metal_steel_steam_hot_water_industry_steel_blastfurnace_bof_parent_share:
  variable: mq_industry_final_demand_for_metal_steel_steam_hot_water_industry_steel_blastfurnace_bof_parent_share
