industry_final_demand_for_metal_steel_network_gas_industry_steel_scrap_hbi_eaf_parent_share:
  variable: mq_industry_final_demand_for_metal_steel_network_gas_industry_steel_scrap_hbi_eaf_parent_share
