industry_aluminium_burner_network_gas_industry_aluminium_smeltoven_electricity_parent_share:
  variable: mq_industry_aluminium_burner_network_gas_industry_aluminium_smeltoven_electricity_parent_share
