industry_final_demand_for_other_paper_electricity_industry_useful_demand_for_other_paper_electricity_parent_share:
  variable: mq_industry_final_demand_for_other_paper_electricity_industry_useful_demand_for_other_paper_electricity_parent_share
