refineries_crude_oil_non_energetic_tj:
  expression: multiply
  components:
    - variable: refineries_co2_scaled
    - variable: mq_refineries_crude_oil_non_energetic_tj

industry_useful_demand_for_chemical_refineries_crude_oil_non_energetic_demand:
  variable: refineries_crude_oil_non_energetic_tj
