refinery_transformation_lpg_tj:
  expression: multiply
  components:
    - variable: refineries_co2_scaled
    - variable: mq_refinery_transformation_lpg_tj

input_industry_refinery_transformation_crude_oil_lpg_demand:
  variable: refinery_transformation_lpg_tj
