fertilizers_wood_pellets_non_energetic_tj:
  expression: multiply
  components:
    - variable: fertilizers_co2_scaled
    - variable: mq_fertilizers_wood_pellets_non_energetic_tj

input_industry_chemical_fertilizers_wood_pellets_non_energetic_demand:
  variable: fertilizers_wood_pellets_non_energetic_tj
