food_electricity_tj:
  expression: multiply
  components:
    - variable: food_co2_scaled
    - variable: mq_food_electricity_tj

input_industry_food_electricity_demand:
  variable: food_electricity_tj
