fertilizers_gas_tj:
  expression: multiply
  components:
    - variable: fertilizers_co2_scaled
    - variable: mq_fertilizers_network_gas_tj

input_industry_chemical_fertilizers_network_gas_demand:
  variable: fertilizers_gas_tj
