fertilizer_wood_pellets_tj:
  expression: multiply
  components:
    - variable: fertilizers_co2_scaled
    - variable: mq_fertilizers_wood_pellets_tj

input_industry_chemical_fertilizers_wood_pellets_demand:
  variable: fertilizer_wood_pellets_tj
