refinery_transformation_diesel_tj:
  expression: multiply
  components:
    - variable: refineries_co2_scaled
    - variable: mq_refinery_transformation_diesel_tj

input_industry_refinery_transformation_crude_oil_diesel_demand:
  variable: refinery_transformation_diesel_tj
