chemical_other_gas_tj:
  expression: multiply
  components:
    - variable: chemical_other_co2_scaled
    - variable: mq_chemical_other_network_gas_tj

input_industry_chemical_other_network_gas_demand:
  variable: chemical_other_gas_tj
