paper_steam_hot_water_tj:
  expression: multiply
  components:
    - variable: paper_co2_scaled
    - variable: mq_paper_steam_hot_water_tj

input_industry_paper_steam_hot_water_demand:
  variable: paper_steam_hot_water_tj
