refinery_transformation_refinery_gas_tj:
  expression: multiply
  components:
    - variable: refineries_co2_scaled
    - variable: mq_refinery_transformation_refinery_gas_tj

input_industry_refinery_transformation_crude_oil_refinery_gas_demand:
  variable: refinery_transformation_refinery_gas_tj
