refinery_transformation_gasoline_tj:
  expression: multiply
  components:
    - variable: refineries_co2_scaled
    - variable: mq_refinery_transformation_gasoline_tj

input_industry_refinery_transformation_crude_oil_gasoline_demand:
  variable: refinery_transformation_gasoline_tj
