paper_wood_pellets_tj:
  expression: multiply
  components:
    - variable: paper_co2_scaled
    - variable: mq_paper_wood_pellets_tj

input_industry_paper_wood_pellets_demand:
  variable: paper_wood_pellets_tj
