fertilizers_steam_hot_water_tj:
  expression: multiply
  components:
    - variable: fertilizers_co2_scaled
    - variable: mq_fertilizers_steam_hot_water_tj

input_industry_chemical_fertilizers_steam_hot_water_demand:
  variable: fertilizers_steam_hot_water_tj
