fertilizers_coal_non_energetic_tj:
  expression: multiply
  components:
    - variable: fertilizers_co2_scaled
    - variable: mq_fertilizers_coal_non_energetic_tj

input_industry_chemical_fertilizers_coal_non_energetic_demand:
  variable: fertilizers_coal_non_energetic_tj
