chemical_other_wood_pellets_tj:
  expression: multiply
  components:
    - variable: chemical_other_co2_scaled
    - variable: mq_chemical_other_wood_pellets_tj

input_industry_chemical_other_wood_pellets_demand:
  variable: chemical_other_wood_pellets_tj
