tp_road_total_bio_ethanol_tj:
  expression: multiply
  components:
    - variable: tp_road_bio_fuels_ex_mm_tj
    - variable: share_bio_ethanol_in_bio_fuels

input_transport_road_bio_ethanol_demand:
  variable: tp_road_total_bio_ethanol_tj
