industry_other_gas_tj:
  expression: multiply
  components:
    - variable: industry_other_co2_scaled
    - variable: mq_industry_other_network_gas_tj

input_industry_other_network_gas_demand:
  variable: industry_other_gas_tj
