input_households_final_demand_steam_hot_water_households_final_demand_for_space_heating_steam_hot_water_parent_share:
  variable: mq_input_households_final_demand_steam_hot_water_households_final_demand_for_space_heating_steam_hot_water_parent_share
