industry_other_electricity_tj:
  expression: multiply
  components:
    - variable: industry_other_co2_scaled
    - variable: mq_industry_other_electricity_tj

input_industry_other_electricity_demand:
  variable: industry_other_electricity_tj
