chemical_other_crude_oil_tj:
  expression: multiply
  components:
    - variable: chemical_other_co2_scaled
    - variable: mq_chemical_other_crude_oil_tj

input_industry_chemical_other_crude_oil_demand:
  variable: chemical_other_crude_oil_tj
