refineries_wood_pellets_tj:
  expression: multiply
  components:
    - variable: refineries_co2_scaled
    - variable: mq_refineries_wood_pellets_tj

input_industry_chemical_refineries_wood_pellets_demand:
  variable: refineries_wood_pellets_tj
