metal_other_electricity_tj:
  expression: multiply
  components:
    - variable: metal_other_co2_scaled
    - variable: mq_metal_other_electricity_tj

input_industry_metal_other_electricity_demand:
  variable: metal_other_electricity_tj
