steel_blastfurnace_coal_tj:
  expression: multiply
  components:
    - variable: steel_co2_scaled
    - variable: mq_steel_blastfurnace_coal_tj

input_energy_blastfurnace_transformation_coal_input_demand:
  variable: steel_blastfurnace_coal_tj
