refineries_gas_tj:
  expression: multiply
  components:
    - variable: refineries_co2_scaled
    - variable: mq_refineries_network_gas_tj

input_industry_chemical_refineries_network_gas_demand:
  variable: refineries_gas_tj
