chemical_other_coal_tj:
  expression: multiply
  components:
    - variable: chemical_other_co2_scaled
    - variable: mq_chemical_other_coal_tj

input_industry_chemical_other_coal_demand:
  variable: chemical_other_coal_tj
