steel_coal_gas_tj:
  expression: multiply
  components:
    - variable: steel_co2_scaled
    - variable: mq_steel_coal_gas_tj

input_industry_metal_steel_coal_gas_demand:
  variable: steel_coal_gas_tj
