industry_other_coal_tj:
  expression: multiply
  components:
    - variable: industry_other_co2_scaled
    - variable: mq_industry_other_coal_tj

input_industry_other_coal_demand:
  variable: industry_other_coal_tj
