steel_chp_coal_gas_tj:
  expression: multiply
  components:
    - variable: steel_co2_scaled
    - variable: mq_steel_chp_coal_gas_tj

input_energy_chp_coal_gas_coal_gas_input_demand:
  variable: steel_chp_coal_gas_tj
