metal_other_gas_tj:
  expression: multiply
  components:
    - variable: metal_other_co2_scaled
    - variable: mq_metal_other_network_gas_tj

input_industry_metal_other_network_gas_demand:
  variable: metal_other_gas_tj
