industry_other_crude_oil_tj:
  expression: multiply
  components:
    - variable: industry_other_co2_scaled
    - variable: mq_industry_other_crude_oil_tj

input_industry_other_crude_oil_demand:
  variable: industry_other_crude_oil_tj
