transport_final_demand_for_rail_electricity_transport_freight_train_using_electricity_parent_share:
  variable: mq_transport_final_demand_for_rail_electricity_transport_freight_train_using_electricity_parent_share
