transport_road_mixer_compressed_network_gas_transport_truck_using_compressed_natural_gas_parent_share:
  variable: mq_transport_road_mixer_compressed_network_gas_transport_truck_using_compressed_natural_gas_parent_share
