# All products and flows that should appear in the Energy Balance. See below for
# other types of energy balance type files, like the network gas commodity balance.
# You can add other types of energy balances here as well

energy_balance:
  unit: TJ
  europe_code: NRG_BAL_C
  products:
    - Total
    #C0000X0350-0370
    - Anthracite
    - Coking coal
    - Other bituminous coal
    - Sub-bituminous coal
    - Lignite
    - Patent fuel
    - Coke oven coke
    - Gas coke
    - Coal tar
    - Brown coal briquettes
    # C0350-0370
    - Gas works gas
    - Coke oven gas
    - Blast furnace gas
    - Other recovered gases
    - Peat and peat products
    #P1100
    #P1200
    - Oil shale and oil sands
    #O4000XBIO
    - Crude oil
    - Natural gas liquids
    - Refinery feedstocks
    - Additives and oxygenates (excluding biofuel portion)
    - Other hydrocarbons
    - Refinery gas
    - Ethane
    - Liquefied petroleum gases
    - Motor gasoline (excluding biofuel portion)
    - Aviation gasoline
    - Gasoline-type jet fuel
    - Kerosene-type jet fuel (excluding biofuel portion)
    - Other kerosene
    - Naphtha
    - Gas oil and diesel oil (excluding biofuel portion)
    - Fuel oil
    - White spirit and special boiling point industrial spirits
    - Lubricants
    - Bitumen
    - Petroleum coke
    - Paraffin waxes
    - Other oil products
    - Natural gas
    #RA000
    - Hydro
    - "Tide, wave, ocean"
    - Wind
    - Solar photovoltaic
    - Solar thermal
    - Geothermal
    - Primary solid biofuels
    - Charcoal
    - Biogases
    - Renewable municipal waste
    - Pure biogasoline
    - Blended biogasoline
    - Pure biodiesels
    - Blended biodiesels
    - Pure bio jet kerosene
    - Blended bio jet kerosene
    - Other liquid biofuels
    - Ambient heat (heat pumps)
    #W6100_6220
    - Industrial waste (non-renewable)
    - Non-renewable municipal waste
    - Nuclear heat
    - Heat
    - Electricity
    #FE: Fossil energy
    #BIOE: Bioenergy
  flows:
    - Primary production
    - Recovered and recycled products
    - Imports
    - Exports
    - Change in stock
    - Gross available energy
    - International maritime bunkers
    - Gross inland consumption
    - International aviation
    - Total energy supply
    - Gross inland consumption (Europe 2020-2030)
    - Primary energy consumption (Europe 2020-2030)
    - Final energy consumption (Europe 2020-2030)
    - Transformation input - energy use
    - Transformation input - electricity and heat generation - energy use
    - Transformation input - electricity and heat generation - main activity producer electricity only - energy use
    - Transformation input - electricity and heat generation - main activity producer combined heat and power - energy use
    - Transformation input - electricity and heat generation - main activity producer heat only - energy use
    - Transformation input - electricity and heat generation - autoproducer electricity only - energy use
    - Transformation input - electricity and heat generation - autoproducer combined heat and power - energy use
    - Transformation input - electricity and heat generation - autoproducer heat only - energy use
    - Transformation input - electricity and heat generation - electrically driven heat pumps
    - Transformation input - electricity and heat generation - electric boilers
    - Transformation input - electricity and heat generation - electricity for pumped storage
    - Transformation input - electricity and heat generation - derived heat for electricity production
    - Transformation input - coke ovens - energy use
    - Transformation input - blast furnaces - energy use
    - Transformation input - gas works - energy use
    - Transformation input - refineries and petrochemical industry - energy use
    - Transformation input - refineries and petrochemical industry - refinery intake - energy use
    - Transformation input - refineries and petrochemical industry - backflows from petrochemical industry - energy use
    - Transformation input - refineries and petrochemical industry - products transferred - energy use
    - Transformation input - refineries and petrochemical industry - interproduct transfers - energy use
    - Transformation input - refineries and petrochemical industry - direct use - energy use
    - Transformation input - refineries and petrochemical industry - petrochemical industry intake - energy use
    - Transformation input - patent fuel plants - energy use
    - Transformation input - brown coal briquettes and peat briquettes plants - energy use
    - Transformation input - coal liquefaction plants - energy use
    - Transformation input - for blended natural gas - energy use
    - Transformation input - liquid biofuels blended - energy use
    - Transformation input - charcoal production plants - energy use
    - Transformation input - gas-to-liquids plants - energy use
    - Transformation input - not elsewhere specified - energy use
    - Transformation output
    - Transformation output - electricity and heat generation
    - Transformation output - electricity and heat generation - main activity producer electricity only
    - Transformation output - electricity and heat generation - main activity producer combined heat and power
    - Transformation output - electricity and heat generation - main activity producer heat only
    - Transformation output - electricity and heat generation - autoproducer electricity only
    - Transformation output - electricity and heat generation - autoproducer combined heat and power
    - Transformation output - electricity and heat generation - autoproducer heat only
    - Transformation output - electricity and heat generation - electrically driven heat pumps
    - Transformation output - electricity and heat generation - electric boilers
    - Transformation output - electricity and heat generation - pumped hydro
    - Transformation output - electricity and heat generation - other sources
    - Transformation output - coke ovens
    - Transformation output - blast furnaces
    - Transformation output - gas works
    - Transformation output - refineries and petrochemical industry
    - Transformation output - refineries and petrochemical industry - refinery output
    - Transformation output - refineries and petrochemical industry - backflows
    - Transformation output - refineries and petrochemical industry - products transferred
    - Transformation output - refineries and petrochemical industry - interproduct transfers
    - Transformation output - refineries and petrochemical industry - primary product receipts
    - Transformation output - refineries and petrochemical industry - petrochemical industry returns
    - Transformation output - patent fuel plants
    - Transformation output - brown coal briquettes and peat briquettes plants
    - Transformation output - coal liquefaction plants
    - Transformation output - blended in natural gas
    - Transformation output - liquid biofuels blended
    - Transformation output - charcoal production plants
    - Transformation output - gas-to-liquids plants
    - Transformation output - not elsewhere specified
    - Energy sector - energy use
    - Energy sector - electricity and heat generation - energy use
    - Energy sector - coal mines - energy use
    - Energy sector - oil and natural gas extraction plants - energy use
    - Energy sector - patent fuel plants - energy use
    - Energy sector - coke ovens - energy use
    - Energy sector - brown coal briquettes and peat briquettes plants - energy use
    - Energy sector - gas works - energy use
    - Energy sector - blast furnaces - energy use
    - Energy sector - petroleum refineries (oil refineries) - energy use
    - Energy sector - nuclear industry - energy use
    - Energy sector - coal liquefaction plants - energy use
    - Energy sector - liquefaction and regasification plants (LNG) - energy use
    - Energy sector - gasification plants for biogas - energy use
    - Energy sector - gas-to-liquids plants - energy use
    - Energy sector - charcoal production plants - energy use
    - Energy sector - not elsewhere specified - energy use
    - Distribution losses
    - Available for final consumption
    - Final consumption - non-energy use
    - Transformation input, energy sector and final consumption in industry sector - non-energy use
    - Transformation input - non-energy use
    - Energy sector - non-energy use
    - Final consumption - industry sector - non-energy use
    - Final consumption - transport sector - non-energy use
    - Final consumption - other sectors - non-energy use
    - Final consumption - energy use
    - Final consumption - industry sector - energy use
    - Final consumption - industry sector - iron and steel - energy use
    - Final consumption - industry sector - chemical and petrochemical - energy use
    - Final consumption - industry sector - non-ferrous metals - energy use
    - Final consumption - industry sector - non-metallic minerals - energy use
    - Final consumption - industry sector - transport equipment - energy use
    - Final consumption - industry sector - machinery - energy use
    - Final consumption - industry sector - mining and quarrying - energy use
    - Final consumption - industry sector - food, beverages and tobacco - energy use
    - Final consumption - industry sector - paper, pulp and printing - energy use
    - Final consumption - industry sector - wood and wood products - energy use
    - Final consumption - industry sector - construction - energy use
    - Final consumption - industry sector - textile and leather - energy use
    - Final consumption - industry sector - not elsewhere specified - energy use
    - Final consumption - transport sector - energy use
    - Final consumption - transport sector - rail - energy use
    - Final consumption - transport sector - road - energy use
    - Final consumption - transport sector - domestic aviation - energy use
    - Final consumption - transport sector - domestic navigation - energy use
    - Final consumption - transport sector - pipeline transport - energy use
    - Final consumption - transport sector - not elsewhere specified - energy use
    - Final consumption - other sectors - energy use
    - Final consumption - other sectors - commercial and public services - energy use
    - Final consumption - other sectors - households - energy use
    - Final consumption - other sectors - agriculture and forestry - energy use
    - Final consumption - other sectors - fishing - energy use
    - Final consumption - other sectors - not elsewhere specified - energy use
    - Statistical differences
    - Gross electricity production
    - Gross electricity production - main activity producer electricity only
    - Gross electricity production - main activity producer combined heat and power
    - Gross electricity production - autoproducer electricity only
    - Gross electricity production - autoproducer combined heat and power
    - Gross heat production
    - Gross heat production - main activity producer combined heat and power
    - Gross heat production - main activity producer heat only
    - Gross heat production - autoproducer combined heat and power
    - Gross heat production - autoproducer heat only

# For the Oil and petroleum products EB download
oil:
  unit: THS_T
  europe_code: NRG_CB_OIL
  flows:
    - Final consumption - industry sector - chemical and petrochemical - non-energy use
    - Final consumption - non-energy use
  products:
    #O4000XBIO
    - Crude oil
    - Natural gas liquids
    - Refinery gas
    - Ethane
    - Liquefied petroleum gases
    - Naphtha
    - Motor gasoline (excluding biofuel portion)
    - Gasoline-type jet fuel
    - Kerosene-type jet fuel (excluding biofuel portion)
    - Other kerosene
    - Gas oil and diesel oil (excluding biofuel portion)
    - Fuel oil
    - White spirit and special boiling point industrial spirits
    - Lubricants
    - Paraffin waxes
    - Petroleum coke
    - Bitumen
    - Other oil products
    - Blended biogasoline
    - Blended biodiesels
    - Blended bio jet kerosene
    - Additives and oxygenates (excluding biofuel portion)
    - Other hydrocarbons

coal:
  unit: THS_T
  europe_code: NRG_CB_SFF
  flows:
    - Final consumption - industry sector - chemical and petrochemical - non-energy use
    - Final consumption - non-energy use
  products:
    # C0000X0350-0370
    - Anthracite
    - Coking coal
    - Other bituminous coal
    - Sub-bituminous coal
    - Lignite
    - Patent fuel
    - Coke oven coke
    - Gas coke
    - Coal tar
    - Brown coal briquettes
    #P1100
    #P1200
    - Oil shale and oil sands

gas:
  unit: TJ_GCV
  europe_code: NRG_CB_GAS
  flows:
    - Final consumption - industry sector - chemical and petrochemical - non-energy use
    - Final consumption - non-energy use
  products:
    #C0350-0370
    - Coke oven gas
    - Gas works gas
    - Blast furnace gas
    - Other recovered gases
    - Natural gas

# Let's see what to do with this cutie
chps:
  unit: MW
  europe_code: NRG_CHP_CPFE
  flows:
    - Maximum gross electricity capacity
    - Maximum gross electricity capacity in CHP mode
    - Maximum net thermal capacity
  products: # gen_tech
    - Total
    - Steam - backpressure turbine
    - Steam - condensing turbine (eff â‰¥ 80%)
    - Internal Combustion CHP
    - Gas Turbine CHP
    - Combined Cycle CHP
    - Other CHP
  extra_attributes:
    efficiencies: ALL+HIGH+LOW
    plants: CHPU+CHPU_HE+CHPU_LE+CHPU_NOP
